export const dailyQuotes = [
	"Roju chesthe result vastundi",
	"Kashtapadu result tappadu ani",
	"Consistency unte success vastundi",
	"Apaku munduku saagu roju",
	"Roju konchem better avvu",
	"Discipline tho gelupu vastundi",
	"Focus pettu result choodu",
	"Start chesav complete cheyyi",
	"Excuses vadili action teesuko",
	"Slow aina munduku vellu",
	"Nee effort waste kaadu",
	"Roju nee best ivvu",
	"Kashtam aina aagaku munduku",
	"Ninnu nuvvu geluvu roju",
	"Oka step munduku veyyi",
	"Pani cheyyi result vastundi",
	"Goal meeda focus pettu roju",
	"Time waste cheyyaku start cheyyi",
	"Nidhana ga aina aagaku",
	"Discipline tho day ni geluvu",
	"Chinna steps pedda results",
	"Ivala effort repu result",
	"Oka roju oka progress",
	"Nee target ni vadulukoku",
	"Action teesuko excuses vaddu",
	"Focus unte daari dorukutundi",
	"Roju practice tho skill perugutundi",
	"Aagipoku nee time vastundi",
	"Hard work eppudu mosam cheyyadu",
	"Consistency tho dream nijam",
	"Mind strong ga unchu",
	"Gelupu kosam daily fight cheyyi",
	"Start small finish strong",
	"Work silent result matladutundi",
	"Ivala chesthe repu gelupu",
	"Oopika pettu progress vastundi",
	"Nee journey ni nammu roju",
	"Nee bhayam kanna, nee kala peddadi.",
	"Nee samayam vastundi, kaadu… techukovali.",
	"Padina prathisari, inka balanga le.",
	"Mugimpu varaku poraadithe, gelupu neede.",
	"Nee kala kosam, prapancham tho poradu.",
	"Nuvvu aagithe, nee katha akkade aagipothundi.",
	"Okkasari gelavaali ante, veyyisaarlu poraadu.",
	"Nee meeda neeku nammakam unte chaalu.",
	"Kashtam ninnu aapadaniki kaadu, penchadaniki.",
	"Gelichevaadu avakaasham kosam eduruchoodadu.",
	"Nee gurinchi nuvve nirnayinchuko, lokam kaadu.",
	"Oka adugu mundukey, daari dorukutundi.",
	"Nuvvu maarithe, nee jeevitham maarutundi.",
	"Nee kalani nijam chese baadhyata neede.",
	"Evaru choodani samayamlo kashtapadu.",
	"Ninna kanna eeroju goppaga undu.",
	"Aagipoye kaaranalu kaadu, mundukelle kaaranam choodu.",
	"Nee limit anedi nee mind lo maatrame.",
	"Gelupu kosam kaadu, nee kosam poraadu.",
];
